# Generated by Django 5.2.17 on 2026-08-05 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('purpose', models.TextField(blank=True, verbose_name='目的')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目標期限')),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '学習中'), ('completed', '完了'), ('suspended', '中断')], default='not_started', max_length=20, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_goals', to='roadmap.category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '学習目標',
                'verbose_name_plural': '学習目標',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(verbose_name='学習日')),
                ('study_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='学習時間（分）')),
                ('learned', models.TextField(verbose_name='学んだこと')),
                ('problem', models.TextField(blank=True, verbose_name='詰まったこと')),
                ('next_action', models.TextField(blank=True, verbose_name='次にやること')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='roadmap.learninggoal', verbose_name='学習目標')),
            ],
            options={
                'verbose_name': '振り返り',
                'verbose_name_plural': '振り返り',
                'ordering': ['-study_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ステップ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='並び順')),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '進行中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='roadmap.learninggoal', verbose_name='学習目標')),
            ],
            options={
                'verbose_name': 'ロードマップステップ',
                'verbose_name_plural': 'ロードマップステップ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タスク名')),
                ('material_url', models.URLField(blank=True, max_length=500, verbose_name='教材URL')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='優先度')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '進行中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.roadmap', verbose_name='ロードマップ')),
            ],
            options={
                'verbose_name': '学習タスク',
                'verbose_name_plural': '学習タスク',
                'ordering': ['due_date', 'id'],
            },
        ),
    ]
